import Navbar from "./auth/Navbar";
import QueryWrapper from "./components/QueryWrapper";
import "./globals.css";
import AuthContext from "./auth/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-4 md:mx-48 xl:mx-96 bg-gray-200">
        <QueryWrapper>
          <AuthContext>
            <Navbar />
            {children}
          </AuthContext>
        </QueryWrapper>
      </body>
    </html>
  );
}
