import Navbar from "./auth/Navbar";
import QueryWrapper from "./components/QueryWrapper";
import "./globals.css";
import Authcontext from "./auth/Authcontext";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export const metadata = {
  title: "Text Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-4 md:mx-48 xl:mx-96 bg-gray-200">
        <QueryWrapper>
          <Authcontext>
            <Navbar />
            {children}
          </Authcontext>
        </QueryWrapper>
      </body>
    </html>
  );
}
